name: Publish Windows Forms App

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --runtime win-x64

    - name: Publish build output
      run: dotnet publish --configuration Release --runtime win-x64 --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-forms-app
        path: ./publish